RENAME TABLE VATLDE.TDTEPP36 TO OLD_TDTEPP36;
CREATE TABLE VATLDE.TDTEPP36 AS (
    SELECT *
    FROM VATLDE.OLD_TDTEPP36
) WITH NO DATA;

CALL SYSPROC.ADMIN_CMD( 'REORG TABLE VATLDE.TDTEPP36' );
ALTER TABLE VATLDE.TDTEPP36 
	ALTER COLUMN ROOMNO SET DATA TYPE CHARACTER(30)
	ALTER COLUMN FLOORNO SET DATA TYPE CHARACTER(30)
	ALTER COLUMN ADDNO SET DATA TYPE CHARACTER(30)
	ALTER COLUMN MOONO SET DATA TYPE CHARACTER(10)
	ALTER COLUMN SOINAM SET DATA TYPE CHARACTER(60)
	ALTER COLUMN TELNO SET DATA TYPE CHARACTER(25)
	ADD COLUMN YAEK VARCHAR(60);