RENAME TABLE VATLDE.TDTEPP01 TO OLD_TDTEPP01;
CREATE TABLE VATLDE.TDTEPP01 AS (
    SELECT *
    FROM VATLDE.OLD_TDTEPP01
) WITH NO DATA;

ALTER TABLE VATLDE.TDTEPP01 ALTER COLUMN ROOMNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP01 ALTER COLUMN FLOORNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP01 ALTER COLUMN ADDNO SET DATA TYPE CHARACTER(30);
CALL SYSPROC.ADMIN_CMD( 'REORG TABLE VATLDE.TDTEPP01' );
ALTER TABLE VATLDE.TDTEPP01 ALTER COLUMN MOONO SET DATA TYPE CHARACTER(10);
ALTER TABLE VATLDE.TDTEPP01 ALTER COLUMN SOINAM SET DATA TYPE CHARACTER(60);
ALTER TABLE VATLDE.TDTEPP01 ALTER COLUMN TELNO SET DATA TYPE CHARACTER(25);
ALTER TABLE VATLDE.TDTEPP01 ADD COLUMN YAEK VARCHAR(60);
