RENAME TABLE VATLDE.TDTEPP30 TO OLD_TDTEPP30;
CREATE TABLE VATLDE.TDTEPP30 AS (
    SELECT *
    FROM VATLDE.OLD_TDTEPP30
) WITH NO DATA;

CALL SYSPROC.ADMIN_CMD( 'REORG TABLE VATLDE.TDTEPP30' );
ALTER TABLE VATLDE.TDTEPP30 
	ALTER COLUMN ROOMNO SET DATA TYPE CHARACTER(30)
	ALTER COLUMN FLOORNO SET DATA TYPE CHARACTER(30)
	ALTER COLUMN ADDNO SET DATA TYPE CHARACTER(30)
	ALTER COLUMN MOONO SET DATA TYPE CHARACTER(10)
	ALTER COLUMN SOINAM SET DATA TYPE CHARACTER(60)
	ALTER COLUMN TELNO SET DATA TYPE CHARACTER(25)
	ADD COLUMN YAEK VARCHAR(60);
