RENAME TABLE VATLDE.TDTEPP012B TO OLD_TDTEPP012B;
CREATE TABLE VATLDE.TDTEPP012B AS (
    SELECT *
    FROM VATLDE.OLD_TDTEPP012B
) WITH NO DATA;


CALL SYSPROC.ADMIN_CMD( 'REORG TABLE VATLDE.TDTEPP012B1' );
ALTER TABLE VATLDE.TDTEPP012B 
	ALTER COLUMN ROOMNO SET DATA TYPE CHARACTER(30)
	ALTER COLUMN FLOORNO SET DATA TYPE CHARACTER(30)
	ALTER COLUMN ADDNO SET DATA TYPE CHARACTER(30)
	ALTER COLUMN MOONO SET DATA TYPE CHARACTER(10)
	ALTER COLUMN SOINAM SET DATA TYPE CHARACTER(60)
	ALTER COLUMN TELNO SET DATA TYPE CHARACTER(25)
	ADD COLUMN YAEK VARCHAR(60);
