RENAME TABLE VATLDE.TDTEDT01 TO OLD_TDTEDT01;
CREATE TABLE VATLDE.TDTEDT01 (
    DLN CHARACTER(42) NOT NULL,
	UID CHARACTER(25),
	FORSTA CHARACTER(2) NOT NULL,
	TIN CHARACTER(13),
	ROOMNO CHARACTER(30),
	FLOORNO CHARACTER(30),
	ADDNO CHARACTER(30),
	POSCOD CHARACTER(5),
	BRANO DECIMAL(5),
	BRAROOMNO CHARACTER(20),
	BRAFLOORNO CHARACTER(20),
	BRAADDNO CHARACTER(20),
	BRAPOSCOD CHARACTER(5),
	TAXTYP CHARACTER(1),
	REQOFFCOD CHARACTER(8),
	OFRCOD CHARACTER(6),
	PRODAT DATE,
	LTOFLG CHARACTER(1),
	LOGINOFFCOD CHARACTER(8),
	DEUSERID CHARACTER(20)
);
