RENAME TABLE VATLDE.TDTEPP01B TO OLD_TDTEPP01B;
CREATE TABLE VATLDE.TDTEPP01B AS (
    SELECT *
    FROM VATLDE.OLD_TDTEPP01B
) WITH NO DATA;

CALL SYSPROC.ADMIN_CMD( 'REORG TABLE VATLDE.TDTEPP01B' );
ALTER TABLE VATLDE.TDTEPP01B 
	ALTER COLUMN ROOMNO SET DATA TYPE CHARACTER(30)
	ALTER COLUMN FLOORNO SET DATA TYPE CHARACTER(30)
	ALTER COLUMN ADDNO SET DATA TYPE CHARACTER(30)
	ALTER COLUMN MOONO SET DATA TYPE CHARACTER(10)
	ALTER COLUMN SOINAM SET DATA TYPE CHARACTER(60)
	ALTER COLUMN TELNO SET DATA TYPE CHARACTER(25)
	ADD COLUMN YAEK VARCHAR(60);
