RENAME TABLE VATLDE.TDTECH01 TO OLD_TDTECH01;
CREATE TABLE VATLDE.TDTECH01  (
    DLN CHARACTER(42) NOT NULL,
	UID CHARACTER(25),
	FORSTA CHARACTER(2) NOT NULL,
	OLDTIN CHARACTER(13),
	ROOMNO CHARACTER(30),
	FLOORNO CHARACTER(30),
	ADDNO CHARACTER(30),
	POSCOD CHARACTER(5),
	TIN CHARACTER(13),
	TAXTYP CHARACTER(1),
	REQOFFCOD CHARACTER(8),
	OFRCOD CHARACTER(6),
	PRODAT DATE,
	LTOFLG CHARACTER(1),
	LOGINOFFCOD CHARACTER(8),
	DEUSERID CHARACTER(20)
);



