RENAME TABLE VATLDE.TDTEPP012 TO OLD_TDTEPP012;
CREATE TABLE VATLDE.TDTEPP012 AS (
    SELECT *
    FROM VATLDE.OLD_TDTEPP012
) WITH NO DATA;

ALTER TABLE VATLDE.TDTEPP012 ALTER COLUMN OVADDNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP012 ADD COLUMN YAEK VARCHAR(60);
