RENAME TABLE VATLDE.TDTECH01 TO OLD_TDTECH01;
CREATE TABLE VATLDE.TDTECH01 AS (
    SELECT *
    FROM VATLDE.OLD_TDTECH01
) WITH NO DATA;

ALTER TABLE VATLDE.TDTECH01 
	ALTER COLUMN ROOMNO SET DATA TYPE CHARACTER(30)
	ALTER COLUMN FLOORNO SET DATA TYPE CHARACTER(30)
	ALTER COLUMN ADDNO SET DATA TYPE CHARACTER(30);