RENAME TABLE VATLDE.TDTEPP012 TO OLD_TDTEPP012;
CREATE TABLE VATLDE.OLD_TDTEPP012 AS (
    SELECT *
    FROM VATLDE.TDTEPP012
) WITH NO DATA;

ALTER TABLE VATLDE.TDTEPP012 ALTER COLUMN OVADDNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP012 ADD COLUMN YAEK VARCHAR(60);
