RENAME TABLE VATLDE.TDTEPP36 TO OLD_TDTEPP36;
CREATE TABLE VATLDE.OLD_TDTEPP36 AS (
    SELECT *
    FROM VATLDE.TDTEPP36
) WITH NO DATA;0

ALTER TABLE VATLDE.TDTEPP36 ALTER COLUMN ROOMNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP36 ALTER COLUMN FLOORNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP36 ALTER COLUMN ADDNO SET DATA TYPE CHARACTER(30);
CALL SYSPROC.ADMIN_CMD( 'REORG TABLE BKVATLDE.TDTEPP36' );
ALTER TABLE VATLDE.TDTEPP36 ALTER COLUMN MOONO SET DATA TYPE CHARACTER(10);
ALTER TABLE VATLDE.TDTEPP36 ALTER COLUMN SOINAM SET DATA TYPE CHARACTER(60);
ALTER TABLE VATLDE.TDTEPP36 ALTER COLUMN TELNO SET DATA TYPE CHARACTER(25);
ALTER TABLE VATLDE.TDTEPP36 ADD COLUMN YAEK VARCHAR(60);