RENAME TABLE VATLDE.TDTEPP012B TO OLD_TDTEPP012B;
CREATE TABLE VATLDE.OLD_TDTEPP012B AS (
    SELECT *
    FROM VATLDE.TDTEPP012B
) WITH NO DATA;

ALTER TABLE VATLDE.TDTEPP012B ALTER COLUMN ROOMNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP012B ALTER COLUMN FLOORNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP012B ALTER COLUMN ADDNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP012B ALTER COLUMN MOONO SET DATA TYPE CHARACTER(10);
ALTER TABLE VATLDE.TDTEPP012B ALTER COLUMN SOINAM SET DATA TYPE CHARACTER(60);
ALTER TABLE VATLDE.TDTEPP012B ALTER COLUMN TELNO SET DATA TYPE CHARACTER(25);
ALTER TABLE VATLDE.TDTEPP012B ADD COLUMN YAEK VARCHAR(60);
