RENAME TABLE VATLDE.TDTECH01 TO OLD_TDTECH01;
CREATE TABLE VATLDE.TDTECH01 AS (
    SELECT *
    FROM VATLDE.OLD_TDTECH01
) WITH NO DATA;

ALTER TABLE VATLDE.TDTECH01 ALTER COLUMN ROOMNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTECH01 ALTER COLUMN FLOORNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTECH01 ALTER COLUMN ADDNO SET DATA TYPE CHARACTER(30);

-----------------------------------------------------------------------------------------

RENAME TABLE VATLDE.TDTEDT01 TO OLD_TDTEDT01;
CREATE TABLE VATLDE.TDTEDT01 AS (
    SELECT *
    FROM VATLDE.OLD_TDTEDT01
) WITH NO DATA;

ALTER TABLE VATLDE.TDTEDT01 ALTER COLUMN ROOMNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEDT01 ALTER COLUMN FLOORNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEDT01 ALTER COLUMN ADDNO SET DATA TYPE CHARACTER(30);

-----------------------------------------------------------------------------------------

RENAME TABLE VATLDE.TDTEPP01 TO OLD_TDTEPP01;
CREATE TABLE VATLDE.TDTEPP01 AS (
    SELECT *
    FROM VATLDE.OLD_TDTEPP01
) WITH NO DATA;

ALTER TABLE VATLDE.TDTEPP01 ALTER COLUMN ROOMNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP01 ALTER COLUMN FLOORNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP01 ALTER COLUMN ADDNO SET DATA TYPE CHARACTER(30);
CALL SYSPROC.ADMIN_CMD( 'REORG TABLE VATLDE.TDTEPP01' );
ALTER TABLE VATLDE.TDTEPP01 ALTER COLUMN MOONO SET DATA TYPE CHARACTER(10);
ALTER TABLE VATLDE.TDTEPP01 ALTER COLUMN SOINAM SET DATA TYPE CHARACTER(60);
ALTER TABLE VATLDE.TDTEPP01 ALTER COLUMN TELNO SET DATA TYPE CHARACTER(25);
ALTER TABLE VATLDE.TDTEPP01 ADD COLUMN YAEK VARCHAR(60);

-----------------------------------------------------------------------------------------

RENAME TABLE VATLDE.TDTEPP01B TO OLD_TDTEPP01B;
CREATE TABLE VATLDE.TDTEPP01B AS (
    SELECT *
    FROM VATLDE.OLD_TDTEPP01B
) WITH NO DATA;

ALTER TABLE VATLDE.TDTEPP01B ALTER COLUMN ROOMNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP01B ALTER COLUMN FLOORNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP01B ALTER COLUMN ADDNO SET DATA TYPE CHARACTER(30);
CALL SYSPROC.ADMIN_CMD( 'REORG TABLE VATLDE.TDTEPP01B' );
ALTER TABLE VATLDE.TDTEPP01B ALTER COLUMN MOONO SET DATA TYPE CHARACTER(10);
ALTER TABLE VATLDE.TDTEPP01B ALTER COLUMN SOINAM SET DATA TYPE CHARACTER(60);
ALTER TABLE VATLDE.TDTEPP01B ALTER COLUMN TELNO SET DATA TYPE CHARACTER(25);
ALTER TABLE VATLDE.TDTEPP01B ADD COLUMN YAEK VARCHAR(60);

-----------------------------------------------------------------------------------------

RENAME TABLE VATLDE.TDTEPP012 TO OLD_TDTEPP012;
CREATE TABLE VATLDE.TDTEPP012 AS (
    SELECT *
    FROM VATLDE.OLD_TDTEPP012
) WITH NO DATA;

ALTER TABLE VATLDE.TDTEPP012 ALTER COLUMN OVADDNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP012 ADD COLUMN YAEK VARCHAR(60);

-----------------------------------------------------------------------------------------

RENAME TABLE VATLDE.TDTEPP012B TO OLD_TDTEPP012B;
CREATE TABLE VATLDE.TDTEPP012B AS (
    SELECT *
    FROM VATLDE.OLD_TDTEPP012B
) WITH NO DATA;

ALTER TABLE VATLDE.TDTEPP012B ALTER COLUMN ROOMNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP012B ALTER COLUMN FLOORNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP012B ALTER COLUMN ADDNO SET DATA TYPE CHARACTER(30);
CALL SYSPROC.ADMIN_CMD( 'REORG TABLE VATLDE.TDTEPP012B' );
ALTER TABLE VATLDE.TDTEPP012B ALTER COLUMN MOONO SET DATA TYPE CHARACTER(10);
ALTER TABLE VATLDE.TDTEPP012B ALTER COLUMN SOINAM SET DATA TYPE CHARACTER(60);
ALTER TABLE VATLDE.TDTEPP012B ALTER COLUMN TELNO SET DATA TYPE CHARACTER(25);
ALTER TABLE VATLDE.TDTEPP012B ADD COLUMN YAEK VARCHAR(60);

-----------------------------------------------------------------------------------------

RENAME TABLE VATLDE.TDTEPP09 TO OLD_TDTEPP09;
CREATE TABLE VATLDE.TDTEPP09 AS (
    SELECT *
    FROM VATLDE.OLD_TDTEPP09
) WITH NO DATA;

ALTER TABLE VATLDE.TDTEPP09 ALTER COLUMN ROOMNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP09 ALTER COLUMN FLOORNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP09 ALTER COLUMN ADDNO SET DATA TYPE CHARACTER(30);

-----------------------------------------------------------------------------------------

RENAME TABLE VATLDE.TDTEPP09B TO OLD_TDTEPP09B;
CREATE TABLE VATLDE.TDTEPP09B AS (
    SELECT *
    FROM VATLDE.OLD_TDTEPP09B
) WITH NO DATA;

ALTER TABLE VATLDE.TDTEPP09B ALTER COLUMN ROOMNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP09B ALTER COLUMN FLOORNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP09B ALTER COLUMN ADDNO SET DATA TYPE CHARACTER(30);
CALL SYSPROC.ADMIN_CMD( 'REORG TABLE VATLDE.TDTEPP09B' );
ALTER TABLE VATLDE.TDTEPP09B ALTER COLUMN MOONO SET DATA TYPE CHARACTER(10);
ALTER TABLE VATLDE.TDTEPP09B ALTER COLUMN SOINAM SET DATA TYPE CHARACTER(60);
ALTER TABLE VATLDE.TDTEPP09B ALTER COLUMN TELNO SET DATA TYPE CHARACTER(25);
ALTER TABLE VATLDE.TDTEPP09B ADD COLUMN YAEK VARCHAR(60);

-----------------------------------------------------------------------------------------

RENAME TABLE VATLDE.TDTEPP091 TO OLD_TDTEPP091;
CREATE TABLE VATLDE.TDTEPP091 AS (
    SELECT *
    FROM VATLDE.OLD_TDTEPP091
) WITH NO DATA;

ALTER TABLE VATLDE.TDTEPP091 ALTER COLUMN ROOMNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP091 ALTER COLUMN FLOORNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP091 ALTER COLUMN ADDNO SET DATA TYPE CHARACTER(30);
CALL SYSPROC.ADMIN_CMD( 'REORG TABLE VATLDE.TDTEPP091' );
ALTER TABLE VATLDE.TDTEPP091 ALTER COLUMN MOONO SET DATA TYPE CHARACTER(10);
ALTER TABLE VATLDE.TDTEPP091 ALTER COLUMN SOINAM SET DATA TYPE CHARACTER(60);
ALTER TABLE VATLDE.TDTEPP091 ALTER COLUMN TELNO SET DATA TYPE CHARACTER(25);
ALTER TABLE VATLDE.TDTEPP091 ADD COLUMN YAEK VARCHAR(60);

-----------------------------------------------------------------------------------------

RENAME TABLE VATLDE.TDTEPP30 TO OLD_TDTEPP30;
CREATE TABLE VATLDE.TDTEPP30 AS (
    SELECT *
    FROM VATLDE.OLD_TDTEPP30
) WITH NO DATA;

ALTER TABLE VATLDE.TDTEPP30 ALTER COLUMN ROOMNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP30 ALTER COLUMN FLOORNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP30 ALTER COLUMN ADDNO SET DATA TYPE CHARACTER(30);
CALL SYSPROC.ADMIN_CMD( 'REORG TABLE VATLDE.TDTEPP30' );
ALTER TABLE VATLDE.TDTEPP30 ALTER COLUMN MOONO SET DATA TYPE CHARACTER(10);
ALTER TABLE VATLDE.TDTEPP30 ALTER COLUMN SOINAM SET DATA TYPE CHARACTER(60);
ALTER TABLE VATLDE.TDTEPP30 ALTER COLUMN TELNO SET DATA TYPE CHARACTER(25);
ALTER TABLE VATLDE.TDTEPP30 ADD COLUMN YAEK VARCHAR(60);

-----------------------------------------------------------------------------------------

RENAME TABLE VATLDE.TDTEPP36 TO OLD_TDTEPP36;
CREATE TABLE VATLDE.TDTEPP36 AS (
    SELECT *
    FROM VATLDE.OLD_TDTEPP36
) WITH NO DATA;

ALTER TABLE VATLDE.TDTEPP36 ALTER COLUMN ROOMNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP36 ALTER COLUMN FLOORNO SET DATA TYPE CHARACTER(30);
ALTER TABLE VATLDE.TDTEPP36 ALTER COLUMN ADDNO SET DATA TYPE CHARACTER(30);
CALL SYSPROC.ADMIN_CMD( 'REORG TABLE VATLDE.TDTEPP36' );
ALTER TABLE VATLDE.TDTEPP36 ALTER COLUMN MOONO SET DATA TYPE CHARACTER(10);
ALTER TABLE VATLDE.TDTEPP36 ALTER COLUMN SOINAM SET DATA TYPE CHARACTER(60);
ALTER TABLE VATLDE.TDTEPP36 ALTER COLUMN TELNO SET DATA TYPE CHARACTER(25);
ALTER TABLE VATLDE.TDTEPP36 ADD COLUMN YAEK VARCHAR(60);